import { RoadmapTopic } from "../../../models";

export const securityJwtBearerClaimsIdentityTopic: RoadmapTopic = {
  id: "topic-dotnet-security-jwt-bearer-claims-identity",
  stepId: "step-mid-security-auth",
  slug: "security-jwt-bearer-claims-identity",
  order: 1,
  title: "JWT Authentication, Claims, Identity & Refresh Token Lifecycle",
  title_fa: "احراز هویت با JWT Bearer، ساختار Claims و چرخه حیات Refresh Token",
  summary:
    "Master stateless JWT token creation and signing (HS256 vs RS256), TokenValidationParameters and ClockSkew, ClaimsPrincipal extraction, Refresh Token Rotation (RTR), automatic reuse breach detection, and HttpOnly cookie session security in .NET 8/9.",
  summary_fa:
    "تسلط عمیق بر احراز هویت بدون وضعیت با JWT (مقایسه HS256 و RS256)، تنظیمات TokenValidationParameters و کاهش ClockSkew، استخراج اطلاعات از ClaimsPrincipal، چرخه چرخش توکن (RTR)، شناسایی نشت امنیتی و ابطال گروهی نشست‌ها در دات‌نت ۸ و ۹.",
  readingTimeMinutes: 32,
  difficulty: "mid",
  content: `## 1. Evolution: From Stateful Session Cookies to Stateless JWT Tokens

In traditional server-rendered web applications (ASP.NET MVC, classic ASP), authentication relied on **Stateful Server Sessions**:

\`\`\`text
[Browser] ── Credentials ──> [Server] ──> Generates Session ID (Stored in Server Memory/Redis)
[Browser] <── Cookie ────── [Server] (Contains session_id=abc123xyz)
\`\`\`

### Limitations of Stateful Server Sessions:
1. **Horizontal Scaling Bottlenecks**: In a multi-server cluster, requests must be routed to the exact same server (Sticky Sessions) or synchronized across a centralized distributed cache (Redis).
2. **CORS & Native Mobile Issues**: Cookies are blocked by cross-origin security rules and do not naturally align with decoupled Mobile apps (iOS/Android) and Single Page Applications (React/Vue/Next.js).

**The Modern Paradigm:** **JSON Web Tokens (JWT / RFC 7519)** provide a self-contained, stateless, cryptographically signed vehicle for transferring user identity between distributed microservices and decoupled clients without requiring database lookups on every single HTTP request.

---

## 2. Anatomy of a JSON Web Token (JWS / RFC 7519)

A JWT is a compact string composed of three distinct Base64Url-encoded segments separated by periods (\`.\`):

\`\`\`text
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
└───────────────┬───────────────────┘ └───────────────────────┬────────────────────────┘ └───────────────────┬──────────────────────┘
             Header                                        Payload                                      Signature
\`\`\`

---

### 1. The Header:
Contains metadata describing the token type and cryptographic algorithm used to sign the token:
\`\`\`json
{
  "alg": "HS256",
  "typ": "JWT"
}
\`\`\`

---

### 2. The Payload (Claims):
Contains the claims (statements about the user and token metadata):
\`\`\`json
{
  "sub": "usr_998124a",
  "email": "developer@enterprise.com",
  "roles": ["Admin", "BillingManager"],
  "jti": "d7e35b1c-992a-4a21-88f1-8f237890abcd",
  "iss": "https://auth.mycompany.com",
  "aud": "https://api.mycompany.com",
  "exp": 1723984500,
  "nbf": 1723983600,
  "iat": 1723983600
}
\`\`\`

- **Standard Registered Claims (RFC 7519)**:
  - \`sub\` (Subject): Unique user identifier.
  - \`jti\` (JWT ID): Unique token identifier used for replay protection and refresh token binding.
  - \`iss\` (Issuer): The identity server that generated the token.
  - \`aud\` (Audience): The specific API services allowed to accept this token.
  - \`exp\` (Expiration Time): Unix timestamp after which the token is invalid.
  - \`nbf\` (Not Before): Unix timestamp before which the token cannot be accepted.

---

### 3. The Signature:
Ensures the message has not been altered in transit. Generated by hashing the Base64Url-encoded header and payload with a secret key:

$$\text{Signature} = \text{HMAC-SHA256}(\text{Base64Url}(\text{Header}) + "." + \text{Base64Url}(\text{Payload}), \text{SecretKey})$$

---

### Signing Algorithms: Symmetric (HS256) vs. Asymmetric (RS256 / ES256)

| Feature | Symmetric (\`HS256\`) | Asymmetric (\`RS256\` / \`ES256\`) |
| :--- | :--- | :--- |
| **Key Type** | Single Shared Secret Key | Public / Private Key Pair |
| **Signing Process** | Auth Server uses Secret Key | Auth Server signs with **Private Key** |
| **Verification Process**| All APIs must possess the **Same Secret Key** | Resource APIs verify using **Public Key (JWKS)** |
| **Security Risk** | Leaking secret from one API compromises all | High security (Public key cannot sign tokens) |
| **Best Architecture** | Monoliths / Internal Private Microservices | Multi-tenant Identity Systems (OpenID Connect / OAuth2) |

---

## 3. Configuring JWT Bearer in ASP.NET Core & Tuning \`TokenValidationParameters\`

To secure your ASP.NET Core API endpoints, register the authentication and authorization middlewares in \`Program.cs\`:

\`\`\`csharp
using System.Text;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = true;
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidIssuer = builder.Configuration["Jwt:Issuer"],

        ValidateAudience = true,
        ValidAudience = builder.Configuration["Jwt:Audience"],

        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(
            Encoding.UTF8.GetBytes(builder.Configuration["Jwt:SecretKey"]!)),

        ValidateLifetime = true,

        // CRITICAL SECURITY FIX: Eliminate default 5-minute clock skew!
        ClockSkew = TimeSpan.FromSeconds(30),

        // Enforce claim types mapping
        NameClaimType = "name",
        RoleClaimType = "roles"
    };
});

builder.Services.AddAuthorization();

var app = builder.Build();

app.UseAuthentication(); // 1. Authenticate identity
app.UseAuthorization();  // 2. Authorize permissions

app.MapGet("/api/secure-data", (ClaimsPrincipal user) => 
    $"Welcome {user.Identity?.Name}, your ID is: {user.FindFirst("sub")?.Value}")
    .RequireAuthorization();
\`\`\`

---

### The Dangerous \`ClockSkew\` Trap:
By default, the .NET JWT validation library applies a **5-minute default \`ClockSkew\`** to tolerate slight time discrepancies across distributed server clocks.
- If an access token is issued with a **15-minute expiration**, the default \`ClockSkew\` allows it to remain valid for **20 minutes**!
- **Security Rule:** Always set \`ClockSkew = TimeSpan.Zero\` or \`TimeSpan.FromSeconds(30)\` in high-security applications.

---

## 4. Extracting Identity via \`ClaimsPrincipal\` & Custom Extension Methods

When an incoming request passes JWT validation, ASP.NET Core constructs a **\`ClaimsPrincipal\`** and populates \`HttpContext.User\`.

\`\`\`csharp
public static class ClaimsPrincipalExtensions
{
    public static Guid GetUserId(this ClaimsPrincipal principal)
    {
        var idClaim = principal.FindFirst("sub")?.Value 
            ?? principal.FindFirst(ClaimTypes.NameIdentifier)?.Value
            ?? throw new UnauthorizedAccessException("User ID claim (sub) is missing.");

        return Guid.Parse(idClaim);
    }

    public static string GetUserEmail(this ClaimsPrincipal principal)
    {
        return principal.FindFirst("email")?.Value 
            ?? principal.FindFirst(ClaimTypes.Email)?.Value
            ?? string.Empty;
    }

    public static IEnumerable<string> GetUserRoles(this ClaimsPrincipal principal)
    {
        return principal.FindAll("roles")
            .Select(c => c.Value)
            .Concat(principal.FindAll(ClaimTypes.Role).Select(c => c.Value));
    }
}
\`\`\`

---

## 5. The Secure Refresh Token Lifecycle: Rotation & Reuse Detection

Because access tokens are completely stateless and cannot be easily revoked before expiration, **Access Tokens must remain short-lived (e.g. 10 to 15 minutes)**.

To maintain continuous user sessions without asking credentials repeatedly, applications use **Refresh Token Rotation (RTR)**.

---

### 1. Database Entity for Refresh Tokens:
\`\`\`csharp
public class RefreshToken
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public string TokenHash { get; set; } = string.Empty; // Store SHA-256 hash of token, NEVER plaintext!
    public string JwtId { get; set; } = string.Empty;     // Binds to access token 'jti' claim
    public Guid UserId { get; set; }
    public User User { get; set; } = null!;
    
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
    public DateTime ExpiresAtUtc { get; set; }
    public bool IsUsed { get; set; }
    public bool IsRevoked { get; set; }
    public string? ReplacedByToken { get; set; }

    public bool IsActive => !IsUsed && !IsRevoked && DateTime.UtcNow < ExpiresAtUtc;
}
\`\`\`

---

### 2. The Refresh Token Rotation & Breach Detection Pipeline:

\`\`\`csharp
public class TokenService(AppDbContext context, IConfiguration config)
{
    public async Task<TokenResponseDto> RefreshTokenAsync(string rawRefreshToken, string expiredAccessToken)
    {
        var tokenHash = HashToken(rawRefreshToken);
        var existingToken = await context.RefreshTokens
            .Include(t => t.User)
            .FirstOrDefaultAsync(t => t.TokenHash == tokenHash);

        if (existingToken == null)
            throw new SecurityTokenException("Invalid refresh token.");

        // BREACH DETECTION: If a previously used refresh token is submitted again,
        // it means an attacker intercepted the token! REVOKE ALL TOKENS FOR THIS USER!
        if (existingToken.IsUsed)
        {
            await RevokeAllUserTokensAsync(existingToken.UserId, "Automatic Reuse Detection Triggered");
            throw new SecurityTokenException("Security alert: Compromised session detected. All sessions terminated.");
        }

        if (!existingToken.IsActive)
            throw new SecurityTokenException("Refresh token is expired or revoked.");

        // 1. Mark current refresh token as USED
        existingToken.IsUsed = true;

        // 2. Generate NEW Access Token and NEW Refresh Token
        var newAccessToken = GenerateAccessToken(existingToken.User);
        var (newRawRefreshToken, newRefreshTokenEntity) = GenerateRefreshToken(existingToken.UserId);

        existingToken.ReplacedByToken = newRefreshTokenEntity.TokenHash;
        context.RefreshTokens.Add(newRefreshTokenEntity);

        await context.SaveChangesAsync();

        return new TokenResponseDto(newAccessToken, newRawRefreshToken);
    }

    private async Task RevokeAllUserTokensAsync(Guid userId, string reason)
    {
        await context.RefreshTokens
            .Where(t => t.UserId == userId && !t.IsRevoked)
            .ExecuteUpdateAsync(s => s.SetProperty(t => t.IsRevoked, true));
    }
}
\`\`\`

---

### 3. Secure Storage: \`HttpOnly\`, \`Secure\`, \`SameSite=Strict\` Cookies
Never store Refresh Tokens in JavaScript \`localStorage\` or \`sessionStorage\` where they are vulnerable to Cross-Site Scripting (XSS) attacks.

Store them in an **HttpOnly Cookie**:
\`\`\`csharp
Response.Cookies.Append("refreshToken", newRawRefreshToken, new CookieOptions
{
    HttpOnly = true,   // JavaScript cannot read this cookie (Prevents XSS theft)
    Secure = true,     // Transmitted ONLY over HTTPS
    SameSite = SameSiteMode.Strict, // Prevents Cross-Site Request Forgery (CSRF)
    Expires = DateTimeOffset.UtcNow.AddDays(7)
});
\`\`\`

---

## 6. Master Comparison Matrix: Authentication Architectures

| Dimension | Stateful Server Sessions | Plain Stateless JWT | JWT + Refresh Token Rotation | BFF Pattern (Token Handler) |
| :--- | :--- | :--- | :--- | :--- |
| **Server Memory Overhead** | High (Session in RAM/Redis) | **Zero (Stateless)** | Very Low (1 DB row per session) | Medium (Gateway Session) |
| **Horizontal Scalability** | Requires Sticky Sessions/Redis | **Infinite (Stateless)** | **Excellent** | Excellent |
| **Instant Revocation Support**| **Instant** | ❌ Impossible until \`exp\` | **Fast (Upon token refresh)** | **Instant (Server-side)** |
| **XSS Vulnerability** | Low (if HttpOnly) | ❌ High (if in localStorage) | **Low (HttpOnly Cookie)** | **Zero (No tokens in browser)** |
| **Complexity** | Low | Low | Medium | High |`,
  content_fa: `## ۱. سیر تکامل: از نشست‌های سروری (Session Cookies) تا توکن‌های بدون وضعیت JWT

در برنامه‌های سنتی تحت وب، احراز هویت با ساخت نشست در حافظه سرور (Stateful Session) و ارسال شناسه کوکی به مرورگر انجام می‌شد:

### معایب نشست‌های سنتی سروری:
۱. **محدودیت مقیاس‌پذیری افقی**: با افزایش تعداد سرورها، درخواست‌ها باید حتماً به همان سرور اولیه ارسال می‌شدند (Sticky Sessions) یا از یک پایگاه داده مشترک مانند Redis استفاده می‌شد.
۲. **ناسازگاری با کلاینت‌های مدرن و موبایل**: کوکی‌ها به راحتی با اپلیکیشن‌های موبایل (iOS/Android) و معماری‌های فرانت‌اند مجزا (React/Next.js) کار نمی‌کنند.

**رویکرد مدرن:** استاندارد **JSON Web Token (JWT / RFC 7519)** یک روش مستقل، سبک و بدون وضعیت (Stateless) است که اطلاعات هویتی کاربر را در قالب یک رشته امضاشده دیجیتال بین میکروسرویس‌ها و کلاینت‌ها منتقل می‌کند.

---

## ۲. کالبدشکافی ساختار سه‌گانه JSON Web Token

یک توکن JWT از سه بخش مجزا تشکیل شده که با علامت نقطه (\`.\`) به یکدیگر متصل می‌شوند:

۱. **بخش Header (سربرگ)**:
   - نوع توکن و الگوریتم امضا را مشخص می‌کند: \`{"alg": "HS256", "typ": "JWT"}\`.
۲. **بخش Payload (کلیم‌ها یا اطلاعات هویتی)**:
   - کلیم‌های استاندارد ثبت‌شده:
     - \`sub\` (Subject): شناسه یکتای کاربر.
     - \`jti\` (JWT ID): شناسه یکتای خود توکن (جهت جلوگیری از Replay Attack).
     - \`iss\` (Issuer): سرور صادرکننده توکن.
     - \`aud\` (Audience): وب‌سرویس‌های مجاز برای پذیرش توکن.
     - \`exp\` (Expiration Time): زمان دقیق انقضای توکن به وقت یونیکس.
۳. **بخش Signature (امضای دیجیتال)**:
   - تضمین می‌کند که هیچ کاربری در طول مسیر نتوانسته محتوای هدر یا کلیم‌ها را دستکاری کند:

$$\text{Signature} = \text{HMAC-SHA256}(\text{Header} + "." + \text{Payload}, \text{SecretKey})$$

---

### مقایسه الگوریتم‌های امضا: متقارن (HS256) در برابر نامتقارن (RS256):
- **الگوریتم متقارن (HS256)**: هر دو سمت (سرور صادرکننده و وب‌سرویس‌ها) از **یک کلید مخفی مشترک** استفاده می‌کنند. مناسب برای سیستم‌های یکپارچه و میکروسرویس‌های خصوصی درون‌سازمانی.
- **الگوریتم نامتقارن (RS256 / RSA)**: سرور احراز هویت با **کلید خصوصی (Private Key)** توکن را امضا کرده و سایر وب‌سرویس‌ها فقط با داشتن **کلید عمومی (Public Key / JWKS)** توکن را اعتبارسنجی می‌کنند. بالاترین سطح امنیت برای سیستم‌های توزیع‌شده و پروتکل OAuth2/OpenID Connect.

---

## ۳. پیکربندی JWT Bearer در ASP.NET Core و تنظیمات حیاتی TokenValidationParameters

\`\`\`csharp
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        options.RequireHttpsMetadata = true;
        options.TokenValidationParameters = new TokenValidationParameters
        {
            ValidateIssuer = true,
            ValidIssuer = builder.Configuration["Jwt:Issuer"],

            ValidateAudience = true,
            ValidAudience = builder.Configuration["Jwt:Audience"],

            ValidateIssuerSigningKey = true,
            IssuerSigningKey = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(builder.Configuration["Jwt:SecretKey"]!)),

            ValidateLifetime = true,

            // نکته حیاتی: کاهش زمان ارفاق پیش‌فرض ۵ دقیقه‌ای ClockSkew به ۳۰ ثانیه!
            ClockSkew = TimeSpan.FromSeconds(30),

            NameClaimType = "name",
            RoleClaimType = "roles"
        };
    });
\`\`\`

### تله خطرناک ClockSkew:
دات‌نت به طور پیش‌فرض یک بازه ارفاق ۵ دقیقه‌ای برای ناهماهنگی ساعت سرورها در نظر می‌گیرد. اگر طول عمر توکن شما ۱۵ دقیقه باشد، با این تنظیم توکن تا **۲۰ دقیقه** معتبر خواهد ماند! برای امنیت بالا، مقدار \`ClockSkew\` باید به کمتر از ۳۰ ثانیه یا صفر تنظیم شود.

---

## ۴. استخراج اطلاعات با ClaimsPrincipal و متدهای توسعه‌یافته

پس از اعتبارسنجی توکن، شیء \`HttpContext.User\` شامل تمامی کلیم‌های کاربر خواهد بود:

\`\`\`csharp
public static class ClaimsPrincipalExtensions
{
    public static Guid GetUserId(this ClaimsPrincipal user) =>
        Guid.Parse(user.FindFirst("sub")?.Value ?? user.FindFirst(ClaimTypes.NameIdentifier)!.Value);

    public static string GetEmail(this ClaimsPrincipal user) =>
        user.FindFirst("email")?.Value ?? string.Empty;
}
\`\`\`

---

## ۵. چرخه حیات Refresh Token: چرخش توکن (RTR) و شناسایی نشت امنیتی (Breach Detection)

از آنجا که توکن‌های دسترسی (Access Token) بدون وضعیت هستند و در صورت سرقت تا زمان \`exp\` معتبر می‌مانند، **طول عمر آن‌ها باید بسیار کوتاه (۱۰ تا ۱۵ دقیقه)** باشد. برای تمدید نشست از الگوی چرخش Refresh Token استفاده می‌شود:

### ۱. سازوکار چرخش Refresh Token (RTR):
به ازای هر بار درخواست تمدید، توکن رفرش قبلی سوزانده شده (\`IsUsed = true\`) و یک جفت توکن جدید (Access Token + Refresh Token تازه) صادر می‌شود.

### ۲. شناسایی نشت امنیتی و ابطال گروهی نشست‌ها (Reuse Detection):
اگر یک Refresh Token که قبلاً استفاده شده است مجدداً به سرور ارسال شود، به این معنی است که توکن توسط یک مهاجم سرقت شده است. سرور بلافاصله **تمامی نشست‌ها و توکن‌های رفرش فعال آن کاربر را به طور خودکار باطل (Revoke) می‌کند** تا مهاجم اخراج شود.

---

### ۳. ذخیره‌سازی امن با کوکی‌های \`HttpOnly\`:
برای جلوگیری از سرقت توکن‌ها توسط حملات تزریق اسکریپت (XSS)، Refresh Token باید در یک کوکی با ویژگی‌های زیر ارسال شود:
- \`HttpOnly = true\`: کدهای جاوااسکریپت در مرورگر به این کوکی دسترسی نخواهند داشت.
- \`Secure = true\`: فقط در بستر پروتکل امن HTTPS منتقل می‌شود.
- \`SameSite = SameSiteMode.Strict\`: محافظت کامل در برابر حملات جعل درخواست (CSRF).

---

## ۶. ماتریس مقایسه جامع معماری‌های احراز هویت

| بعد مقایسه | نشست‌های سروری (Session) | توکن ساده JWT | ترکیب JWT با Refresh Token Rotation |
| :--- | :--- | :--- | :--- |
| **مصرف رم در سرور** | بالا (نگهداری Session در رم/ردیس) | **صفر (کاملاً Stateless)** | بسیار اندک (یک رکورد در دیتابیس) |
| **مقیاس‌پذیری افقی** | نیازمند کلاستر ردیس یا Sticky Session | **نامحدود و آنی** | **بسیار بالا** |
| **امکان ابطال دسترسی کاربر**| **آنی و در لحظه** | ❌ ناممکن تا پایان زمان \`exp\` | **سریع (در اولین تلاش تمدید)** |
| **امنیت در برابر XSS** | بالا (با کوکی HttpOnly) | ❌ ضعیف (در صورت ذخیره در localStorage) | **بسیار بالا (با کوکی HttpOnly)** |`,
};
